# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abc < Formula
  desc "CLI for Apple Business Connect API - manage business presence on Apple Maps"
  homepage "https://github.com/dl-alexandre/Apple-Business-Connect-CLI"
  version "v0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.14/abc-darwin-amd64.tar.gz"
      sha256 "1cd6eae16e11e4ef6b005435059996d7c37877812dbf24ace37648cd36ee901d"

      define_method(:install) do
        bin.install "abc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.14/abc-darwin-arm64.tar.gz"
      sha256 "ce1b9820a5cfa44c1cbea596b6a45c2025c9dd9bd07be37b5be0d250de9aefb9"

      define_method(:install) do
        bin.install "abc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.14/abc-linux-amd64.tar.gz"
      sha256 "cd798fafb7fe3a14c262585f60da88b49cb955715ace2dc553894bbdaeecade8"
      define_method(:install) do
        bin.install "abc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.14/abc-linux-arm64.tar.gz"
      sha256 "13951c071b20fec4ee036189e169db6243b072a16c281ac00867e4f51a7f515c"
      define_method(:install) do
        bin.install "abc"
      end
    end
  end

  test do
    system "#{bin}/abc", "version"
  end
end
