# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abc < Formula
  desc "CLI for Apple Business Connect API"
  homepage "https://github.com/dl-alexandre/Apple-Business-Connect-CLI"
  version "v0.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.15/abc-darwin-amd64.tar.gz"
      sha256 "52aed2205cb2d80760fb44d756dc65d22a28878d6da512d30b597ac93d601ede"

      define_method(:install) do
        bin.install "abc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.15/abc-darwin-arm64.tar.gz"
      sha256 "b28d8d31fdbf6e50c5a8d5e6a958a9074ccebaf09efb651b36620a9519ddf7a1"

      define_method(:install) do
        bin.install "abc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.15/abc-linux-amd64.tar.gz"
      sha256 "e2fa2a4bcaa340833e28dc5db56ccf6065399c1a15bdb1fa7359b45ff1c7caee"
      define_method(:install) do
        bin.install "abc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Apple-Business-Connect-CLI/releases/download/v0.0.15/abc-linux-arm64.tar.gz"
      sha256 "15472d1fb28bc1e4be3c4bfee1381a18db66f29059e148240ce355f24b0a43dd"
      define_method(:install) do
        bin.install "abc"
      end
    end
  end

  test do
    system "#{bin}/abc", "version"
  end
end
