# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "CLI for the App Store Server API"
  homepage "https://github.com/dl-alexandre/App-StoreKit-CLI"
  version "v0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.9/ask-darwin-amd64.tar.gz"
      sha256 "165021f8bd89526a99aeecc2ad9b817d67c17ed1cca523fee0bf23dee7878b27"

      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.9/ask-darwin-arm64.tar.gz"
      sha256 "c60e4d3e07ed1f4bae08a22b295108107ed7ef850cabe59961c2b2921d8fd8db"

      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.9/ask-linux-amd64.tar.gz"
      sha256 "463e588f26df4e3ebe73a20f067f971c9434519d98f8eaf3a9d6bb0ca73234b2"
      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.9/ask-linux-arm64.tar.gz"
      sha256 "6b91055c0617797d9b62a1be00e094300edffe717bd7cdd351b6ede1eaa96793"
      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "version"
  end
end
