# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "CLI for the App Store Server API"
  homepage "https://github.com/dl-alexandre/App-StoreKit-CLI"
  version "v0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.8/ask-darwin-amd64.tar.gz"
      sha256 "a05f6fab64f65ab3ceb52c76eefe5531e18174f97ef6367311fcf79e9f9d15e3"

      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.8/ask-darwin-arm64.tar.gz"
      sha256 "879754bc28c8c3dfd0e8fa6dc0d00665073496719b417ca7f78352faeb5771d4"

      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.8/ask-linux-amd64.tar.gz"
      sha256 "6dc2d9a24a2a11663fbd49c890f1b032f2dcb2534c41d65c60d9056677374325"
      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/App-StoreKit-CLI/releases/download/v0.0.8/ask-linux-arm64.tar.gz"
      sha256 "68a4a6359185b08584df526c0da1b0fbbec66224b9d30f17393b7f5ca407f995"
      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "version"
  end
end
