# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliTemplate < Formula
  desc "Production-ready Go CLI template with Kong, Viper, caching, and GoReleaser"
  homepage "https://github.com/dl-alexandre/cli-template"
  version "v1.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.4/cli-template_Darwin_x86_64.tar.gz"
      sha256 "0fab45921003d3a2ca576a345e6ea5568ed194647eae8a5622a7128a2267d25a"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.4/cli-template_Darwin_arm64.tar.gz"
      sha256 "1d30c89641d655b6ec69211cc17a411e360a0d13ff6c1533d6943b5a21ccfe5b"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.4/cli-template_Linux_x86_64.tar.gz"
      sha256 "d9f47157a9af4cb2f1bb0e01fb821e6c17f41c61ffb526459dfd6b1addd2b2c6"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.4/cli-template_Linux_arm64.tar.gz"
      sha256 "ef49e850770abecfdeb31b4c9988f50186bee348b7b416f7514cf09730ecc325"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  test do
    system "#{bin}/cli-template", "version"
  end
end
