# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliTemplate < Formula
  desc "Production-ready Go CLI template with Kong, Viper, caching, and GoReleaser"
  homepage "https://github.com/dl-alexandre/cli-template"
  version "v1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.2/cli-template_Darwin_x86_64.tar.gz"
      sha256 "c2be2988f93fc7139f588ee17725b6b0b92e5d30979d17037de84b563ac07e7b"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.2/cli-template_Darwin_arm64.tar.gz"
      sha256 "0f19971a4340c4e0d9b0d00ec9542d95624c3b8d46846af5d727c01363ea7bc0"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.2/cli-template_Linux_x86_64.tar.gz"
      sha256 "5a10bdb13b2fb078297da6083f17f6d8fa7ca7e9602600c5ce78b3370444f7cb"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.2/cli-template_Linux_arm64.tar.gz"
      sha256 "96a6544b8b0e4b8dcaa3ce467848dc111c15aeb7e91c1fff8f3e278afe56464a"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  test do
    system "#{bin}/cli-template", "version"
  end
end
