# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliTemplate < Formula
  desc "Production-ready Go CLI template with Kong, Viper, caching, and GoReleaser"
  homepage "https://github.com/dl-alexandre/cli-template"
  version "v1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.3/cli-template_Darwin_x86_64.tar.gz"
      sha256 "689a236452c8a03cc49ce69121d3085a7e0861f38a672e470c57579325b06d4f"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.3/cli-template_Darwin_arm64.tar.gz"
      sha256 "7ea5e24ccdee35b47bc97ee25c2f3d78ecebbc837772f11a9a77b2017fd5b584"

      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.3/cli-template_Linux_x86_64.tar.gz"
      sha256 "ca159910824ad8b3144de11aa0c01fe704b68fcaebe732a9d0f8379330f8b579"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/cli-template/releases/download/v1.1.3/cli-template_Linux_arm64.tar.gz"
      sha256 "68799e60a2ae9aedc7873522ed07ddff887236d1b46f96ab4392ad71bc7e4c5a"
      define_method(:install) do
        bin.install "cli-template"
      end
    end
  end

  test do
    system "#{bin}/cli-template", "--help"
  end
end
