# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdrv < Formula
  desc "Fast, lightweight CLI for Google Drive"
  homepage "https://github.com/dl-alexandre/Google-Drive-CLI"
  version "v0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.7.0/gdrv-darwin-amd64.tar.gz"
      sha256 "a3ae60e0c0b2e502c61d4c9490ed47116664ad91f13d5c0c5d3589f47b5e183e"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.7.0/gdrv-darwin-arm64.tar.gz"
      sha256 "28d8a474656997d7e93a37c6261619e0f9ed92634d690ebb70422e39d77e4e62"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.7.0/gdrv-linux-amd64.tar.gz"
      sha256 "c436153bf1b2f7fb30f7e0aa71c370c9f8bc7c86943ce07f3034c00d01bc809e"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.7.0/gdrv-linux-arm64.tar.gz"
      sha256 "163174c23b96037368c4ec2f4db14863027cf61abfecd28e63ead3d6077813f9"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  test do
    system "#{bin}/gdrv", "--help"
  end
end
