# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdrv < Formula
  desc "Fast, lightweight CLI for Google Drive"
  homepage "https://github.com/dl-alexandre/Google-Drive-CLI"
  version "v0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.4/gdrv-darwin-amd64.tar.gz"
      sha256 "61bfa5957fd713121f51ca2335430f8942a9f949af6c760f3c18c1c9172b3ba4"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.4/gdrv-darwin-arm64.tar.gz"
      sha256 "8f426a85d6affa3a451c5a3e37b0d96fb3eb63c84e992207b8c6df9615a4bccd"

      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.4/gdrv-linux-amd64.tar.gz"
      sha256 "2606b2974f239f1f8f22bbc5e8347cae03cb966e315571b6dad9bf1dbf589ce1"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Drive-CLI/releases/download/v0.6.4/gdrv-linux-arm64.tar.gz"
      sha256 "cc7254956d51e1dc2c0f74306da649206d2fbd0e787784d15d7a78f6072a888f"
      define_method(:install) do
        bin.install "gdrv"
      end
    end
  end

  test do
    system "#{bin}/gdrv", "version"
  end
end
