# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpd < Formula
  desc "Google Play Developer CLI - fast, lightweight CLI for Google Play Console"
  homepage "https://github.com/dl-alexandre/gpd"
  version "v0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.4.6/gpd_0.4.6_darwin_x86_64.tar.gz"
      sha256 "8835098cc8a6604bc0f85e1f45fd99dee9dc1f5ee03abcb3e59c71d9e3fba7ba"

      define_method(:install) do
        bin.install "gpd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.4.6/gpd_0.4.6_darwin_arm64.tar.gz"
      sha256 "439e5cb01f1b3cb20b3d22ee0af2a29df8f18f0d63bcebc69c69c1997621ffe1"

      define_method(:install) do
        bin.install "gpd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.4.6/gpd_0.4.6_linux_x86_64.tar.gz"
      sha256 "b3572f171b8373936758cc2ca06bf348a94055fd15f0a181cb23959f2ff63574"
      define_method(:install) do
        bin.install "gpd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Google-Play-Developer-CLI/releases/download/v0.4.6/gpd_0.4.6_linux_arm64.tar.gz"
      sha256 "4f018fa2579131424f56ee14eb97bef437475b48da802b9c5a7d9d19e056baa4"
      define_method(:install) do
        bin.install "gpd"
      end
    end
  end

  test do
    system "#{bin}/gpd", "version"
  end
end
