# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grokipedia < Formula
  desc "Grokipedia CLI - command-line interface for the Grokipedia API"
  homepage "https://github.com/dl-alexandre/Grokipedia-CLI"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.5/grokipedia_0.0.5_darwin_x86_64.tar.gz"
      sha256 "e8ee0ebd2c5602f48af476ec08fcfc7223736ea06b579033148e578d3f3c2694"

      define_method(:install) do
        bin.install "grokipedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.5/grokipedia_0.0.5_darwin_arm64.tar.gz"
      sha256 "66c26d6ac9949543d6ffa6c80002c59608edbde3720fb84c4006359892691a1e"

      define_method(:install) do
        bin.install "grokipedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.5/grokipedia_0.0.5_linux_x86_64.tar.gz"
      sha256 "b1a6aef23a8d1bf1acf59b7367ef6dd7f66fdf7eec84f94dc8730c09c2217163"
      define_method(:install) do
        bin.install "grokipedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Grokipedia-CLI/releases/download/v0.0.5/grokipedia_0.0.5_linux_arm64.tar.gz"
      sha256 "27995e98041e3d3b2f9c489da28855abc5fdaa2d7b0eb6d7670893a166da6fea"
      define_method(:install) do
        bin.install "grokipedia"
      end
    end
  end

  test do
    system "#{bin}/grokipedia", "--help"
  end
end
