# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpr < Formula
  desc "CLI for USDA AMS MyMarketNews Datamart API"
  homepage "https://github.com/dl-alexandre/MyMarketNews-CLI"
  version "v0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.8/mpr-darwin-amd64.tar.gz"
      sha256 "5c6f5f367f77ccf7b21ffcac2f72d9f2909623cafb1e65f62db6b0a3b8f971b3"

      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.8/mpr-darwin-arm64.tar.gz"
      sha256 "f83d9418bc05b698722b563db1c660265f87cdd67304a02d8bc8adade5adfa5f"

      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.8/mpr-linux-amd64.tar.gz"
      sha256 "2a110672cb8dffc8c7c04a7449d0dae2b92d06b47dd31aca03b686bed0d3928a"
      define_method(:install) do
        bin.install "mpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/MyMarketNews-CLI/releases/download/v0.0.8/mpr-linux-arm64.tar.gz"
      sha256 "d35f5507c1ef6feb4bd22659c0faf4800ced450b5380397a44a194f8955c2104"
      define_method(:install) do
        bin.install "mpr"
      end
    end
  end

  test do
    system "#{bin}/mpr", "version"
  end
end
