# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unifi < Formula
  desc "Local UniFi Controller CLI"
  homepage "https://github.com/dl-alexandre/Local-UniFi-CLI"
  version "v0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.8/unifi-darwin-amd64.tar.gz"
      sha256 "3ef58cf8ffe68e5e88c918aeac5d7074bab0fc1fa8ae955c360b514df2886ec5"

      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.8/unifi-darwin-arm64.tar.gz"
      sha256 "acf8689a4dca1adc935137e4e06e984a05e1ea367f46d1ae774debe81c72c984"

      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.8/unifi-linux-amd64.tar.gz"
      sha256 "0ec5b1d69cc005fae381c34b84bacb16962deaf3a306717a263d03ac86c0842e"
      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.0.8/unifi-linux-arm64.tar.gz"
      sha256 "a7d804522a50d2ec679f2770ed806e39c82f16d31f16bba2316d8369abc38dfb"
      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  test do
    system "#{bin}/unifi", "version"
  end
end
