# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unifi < Formula
  desc "CLI for local UniFi controller management"
  homepage "https://github.com/dl-alexandre/Local-UniFi-CLI"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-darwin-amd64.tar.gz"
      sha256 "d920075402f6c517e60595ba1bf37a7861901cb4b8c05fc674b63a5467699bb5"

      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-darwin-arm64.tar.gz"
      sha256 "be0dcc8f76c90250bbaf5c9d390f25c8ca4d1a3fad811f335d21d21097c8772b"

      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-linux-amd64.tar.gz"
      sha256 "e0afb7819eb4bc9b00291fc12ea4ff847553fe1fa9fae73af3a546a38ac54c86"
      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-linux-arm64.tar.gz"
      sha256 "7120c2cfe4f558afcdc248fc35e586756d2827ec6bf161c4c9a3a811a7aa9dd4"
      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  test do
    system "#{bin}/unifi", "version"
  end
end
