# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unifi < Formula
  desc "CLI for local UniFi controller management"
  homepage "https://github.com/dl-alexandre/Local-UniFi-CLI"
  version "v0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-darwin-amd64.tar.gz"
      sha256 "cfda096935a8dfb9eea53532fb7a86198fe36ea3c9f0375b541753d94bd0662c"

      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-darwin-arm64.tar.gz"
      sha256 "60d460812b14c8b2f9607350c009124c7ec15c901f2e5d47a1c79bcdffd3533d"

      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-linux-amd64.tar.gz"
      sha256 "98a18ab8be0f5c383eea00802e187c312845aa05b7b45c3c4504861d8fbf53d7"
      define_method(:install) do
        bin.install "unifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/Local-UniFi-CLI/releases/download/v0.1.7/unifi-linux-arm64.tar.gz"
      sha256 "59e48646aac0fdb3a222a914d7aaf2eb74b610d8815714d48bca4debcedfe75a"
      define_method(:install) do
        bin.install "unifi"
      end
    end
  end

  test do
    system "#{bin}/unifi", "version"
  end
end
