# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ups < Formula
  desc "UPS CLI - Track packages and manage UPS shipments"
  homepage "https://github.com/dl-alexandre/UPS-CLI"
  version "v0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.7/ups_Darwin_x86_64.tar.gz"
      sha256 "2c72b152496568a9dfb82d254030025ebc669eab58aa9c254c35bf006fd71b52"

      define_method(:install) do
        bin.install "ups"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.7/ups_Darwin_arm64.tar.gz"
      sha256 "4639456ec52a60bd477193eb4205cc923538b6476cf5a87d5bab51d5ee66f224"

      define_method(:install) do
        bin.install "ups"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.7/ups_Linux_x86_64.tar.gz"
      sha256 "3221eccdab6e9dafdf9e43a8a47a94e5b98b221eb3cc685833ae55aac29fa494"
      define_method(:install) do
        bin.install "ups"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.7/ups_Linux_arm64.tar.gz"
      sha256 "198dbd9cae5d5c8666c7bfb9610172bdf35a89fc9b739abaf6b3a878ed5895f4"
      define_method(:install) do
        bin.install "ups"
      end
    end
  end

  test do
    system "#{bin}/ups", "version"
  end
end
