# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ups < Formula
  desc "UPS CLI - Track packages and manage UPS shipments"
  homepage "https://github.com/dl-alexandre/UPS-CLI"
  version "v0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.6/ups_Darwin_x86_64.tar.gz"
      sha256 "5408c09bb6e854c4389dfc6d32304454e018a45e8ee850ef7abcbafc49090bd0"

      define_method(:install) do
        bin.install "ups"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.6/ups_Darwin_arm64.tar.gz"
      sha256 "db2562c8102080bd44cf17a37fb1c82b87557c850154bb7433871102ed1e50c5"

      define_method(:install) do
        bin.install "ups"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.6/ups_Linux_x86_64.tar.gz"
      sha256 "4b51dee4be44e05f6959c11465d00a396b76c8e8c8d8dd13690cd3308ad58159"
      define_method(:install) do
        bin.install "ups"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UPS-CLI/releases/download/v0.0.6/ups_Linux_arm64.tar.gz"
      sha256 "a172322991a78007964e643bae892ea4d1adf0c0b8295ed85d7682b4015b18cd"
      define_method(:install) do
        bin.install "ups"
      end
    end
  end

  test do
    system "#{bin}/ups", "version"
  end
end
