# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usm < Formula
  desc "Full-featured CLI for managing UniFi networks via Site Manager API"
  homepage "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI"
  version "v1.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.7/usm-darwin-amd64.tar.gz"
      sha256 "b7da256c18aa8359b235d1ab9673cfacd63b1643421cd3432a03361632c6f443"

      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.7/usm-darwin-arm64.tar.gz"
      sha256 "2c1cc0ea9f74e050bf1430ba1b83914b99d0fe36d004b7ba7709172981837a25"

      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.7/usm-linux-amd64.tar.gz"
      sha256 "b0326023f348a6cbf62072a8b6234ab4f4d71039486d067a8737687e5ef7bc43"
      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.7/usm-linux-arm64.tar.gz"
      sha256 "e402acb7e514b9c3f4097718fbc9eca0da4f2d8eaf709c406828b74165de8b03"
      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  test do
    system "#{bin}/usm", "--help"
  end
end
