# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usm < Formula
  desc "Full-featured CLI for managing UniFi networks via Site Manager API"
  homepage "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI"
  version "v1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-darwin-amd64.tar.gz"
      sha256 "89861f5d4eb1bb689ad44b682432b6c7df61164e03a0bae3873c4f34280b8963"

      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-darwin-arm64.tar.gz"
      sha256 "e058e773313ae59a7e863ba408df67c2f8588ca79c376238caa1a02a242875be"

      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-linux-amd64.tar.gz"
      sha256 "5a0a764c4e9674456e01bd0dd6bfd3099bcbf90b72a0629909924dce62e7a798"
      define_method(:install) do
        bin.install "usm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/UniFi-Site-Manager-CLI/releases/download/v1.1.2/usm-linux-arm64.tar.gz"
      sha256 "942b671ed5e84c4015e1f4b3af59fed7b6644a5e92fa0b0fb172b64c1cd6ce4e"
      define_method(:install) do
        bin.install "usm"
      end
    end
  end

  test do
    system "#{bin}/usm", "version"
  end
end
