# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XCli < Formula
  desc "Terminal-first CLI for X with AI-friendly outputs"
  homepage "https://github.com/dl-alexandre/X-CLI"
  version "v0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.3/x_Darwin_x86_64.tar.gz"
      sha256 "0cb4c94294cc6bf8540cb93696e795811db4e6195f5dfe619df731a6c94c4e9c"

      define_method(:install) do
        bin.install "x"
        bash_completion.install "completions/x.bash" => "x"
        zsh_completion.install "completions/_x" => "_x"
        fish_completion.install "completions/x.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.3/x_Darwin_arm64.tar.gz"
      sha256 "4cbb19bbf8cbbbd807d072ba36783c9d09862bacd5f09c7a240e8be3e368d365"

      define_method(:install) do
        bin.install "x"
        bash_completion.install "completions/x.bash" => "x"
        zsh_completion.install "completions/_x" => "_x"
        fish_completion.install "completions/x.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.3/x_Linux_x86_64.tar.gz"
      sha256 "380e7b3f47eb405c043108f41afe13ed373ee872771124f28c45fffecba4104e"
      define_method(:install) do
        bin.install "x"
        bash_completion.install "completions/x.bash" => "x"
        zsh_completion.install "completions/_x" => "_x"
        fish_completion.install "completions/x.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dl-alexandre/X-CLI/releases/download/v0.0.3/x_Linux_arm64.tar.gz"
      sha256 "fc5c73efe951c826a95b3395db95f7b59c58576d9fc5744aee83f89702d35e86"
      define_method(:install) do
        bin.install "x"
        bash_completion.install "completions/x.bash" => "x"
        zsh_completion.install "completions/_x" => "_x"
        fish_completion.install "completions/x.fish"
      end
    end
  end

  test do
    system "#{bin}/x", "version"
  end
end
